variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - package

package:
  stage: package
  image: docker:latest
  variables:
    LANG: C.UTF-8
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -f _docker/Backend -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - develop

