channels:
- conda-forge
- main
dependencies:
- django=3.2.5
- beautifulsoup4=4.9.3
- base58=2.1.0
- psycopg2=2.8.6
- django-model-utils=4.0.0
- python-levenshtein=0.12.0
- html2text=2020.1.16
- django-extensions=3.0.9
- psutil=5.8.0
- whitenoise=5.2.0
- python-dotenv=0.15.0
- validators=0.18.1
- black=21.7b0
- click=8.0.1
- codecov=2.1.11
- dill=0.3.4
- gcsfs=2021.7.0
- geckodriver=0.29.0
- ipython=7.25.0
- leveldb=1.23
- multiprocess=0.70.12.2
- mypy=0.910
- nodejs=14.17.1
- pandas=1.3.0
- pillow=8.3.1
- pip=21.1.3
- pre-commit=2.13.0
- pyarrow=4.0.1
- pytest-asyncio=0.15.1
- pytest-cov=2.12.1
- pytest=6.2.4
- python=3.9.6
- pyvirtualdisplay=2.2
- recommonmark=0.7.1
- redis-py=3.5.3
- s3fs=2021.7.0
- selenium=3.141.0
- sentry-sdk=1.3.1
- sphinx-markdown-tables=0.0.15
- sphinx=4.1.1
- tabulate=0.8.9
- tblib=1.7.0
- wget=1.20.3
- pip:
  - django-common-helpers==0.9.2
  - django-cron==0.5.1
  - names==0.3.0
  - tldextract==2.2.2
  - django-countries==6.1.3
  - django-filter==2.4.0
  - django-tables2==2.4.0
  - django-bootstrap4==2.3.1
  - dataclasses-json==0.5.4
  - domain-utils==0.7.1
  - jsonschema==3.2.0
  - plyvel==1.3.0
  - types-pyyaml==5.4.3
  - types-redis==3.5.4
  - types-tabulate==0.1.1
name: privacymail
